### ISSUE TITLE
Error when loading JS code containing a regular expression in a template

### ISSUE THREAD

**Issue by florianeckerstorfer** [theserverlessway/formica#157]
I have the following template which loads the source code for a lambda function using `code`:

```yaml
Resources:
  FormicaJsRegExpLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: node10
      Code:
        ZipFile: "{{ code('code.js') }}"
```

`code.js` looks like this:

```js
exports.handler = (event, context, callback) => {
    return "foobar/12".match(/\d+/);
};
```

When I run `formica template` I get the following error ❌ :

```shell
while scanning a double-quoted scalar
  in "<unicode string>", line 8, column 18:
            ZipFile: "const path = require(\"path\"); ...
                     ^
found unknown escape character 'd'
  in "<unicode string>", line 8, column 138:
     ...    return \"foobar/12\".match(/\d+/);\n};"
                                         ^
Following is the Yaml document formica is trying to load:
```shell
---------------------------------------------------------------------------
Resources:
  FormicaJsRegExpLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: node10
      Code:
        ZipFile: "const path = require(\"path\");\n\nexports.handler = (event, context, callback) => {\n    return \"foobar/12\".match(/\d+/);\n};"
---------------------------------------------------------------------------
```

When I embed the function directly in the template the code is correctly escaped ✅ :

```yaml
Resources:
  FormicaJsRegExpLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: node10
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
            return "foobar/12".match(/\d+/);
          };

```
